// data.js
const items = [
    { id: 1, name: 'Andhra Pradesh', state: 'Andhra Pradesh', content: 'Content for Andhra Pradesh', link: 'https://www.example.com/andhra-pradesh' },
    { id: 2, name: 'Arunachal Pradesh', state: 'Arunachal Pradesh', content: 'Content for Arunachal Pradesh', link: 'https://www.example.com/arunachal-pradesh' },
    { id: 3, name: 'Assam', state: 'Assam', content: 'Content for Assam', link: 'https://www.example.com/assam' },
    { id: 4, name: 'Bihar', state: 'Bihar', content: 'Content for Bihar', link: 'https://www.example.com/bihar' },
    { id: 5, name: 'Chhattisgarh', state: 'Chhattisgarh', content: 'Content for Chhattisgarh', link: 'https://www.example.com/chhattisgarh' },
    { id: 6, name: 'Goa', state: 'Goa', content: 'Content for Goa', link: 'https://www.example.com/goa' },
    { id: 7, name: 'Gujarat', state: 'Gujarat', content: 'Content for Gujarat', link: 'https://www.example.com/gujarat' },
    { id: 8, name: 'Haryana', state: 'Haryana', content: 'Content for Haryana', link: 'https://www.example.com/haryana' },
    { id: 9, name: 'Himachal Pradesh', state: 'Himachal Pradesh', content: 'Content for Himachal Pradesh', link: 'https://www.example.com/himachal-pradesh' },
    { id: 10, name: 'Jharkhand', state: 'Jharkhand', content: 'Content for Jharkhand', link: 'https://www.example.com/jharkhand' },
    { id: 11, name: 'Karnataka', state: 'Karnataka', content: 'Content for Karnataka', link: 'https://www.example.com/karnataka' },
    { id: 12, name: 'Kerala', state: 'Kerala', content: 'Content for Kerala', link: 'https://www.example.com/kerala' },
    { id: 13, name: 'Madhya Pradesh', state: 'Madhya Pradesh', content: 'Content for Madhya Pradesh', link: 'https://www.example.com/madhya-pradesh' },
    { id: 14, name: 'Maharashtra', state: 'Maharashtra', content: 'Content for Maharashtra', link: 'https://www.example.com/maharashtra' },
    { id: 15, name: 'Manipur', state: 'Manipur', content: 'Content for Manipur', link: 'https://www.example.com/manipur' },
    { id: 16, name: 'Meghalaya', state: 'Meghalaya', content: 'Content for Meghalaya', link: 'https://www.example.com/meghalaya' },
    { id: 17, name: 'Mizoram', state: 'Mizoram', content: 'Content for Mizoram', link: 'https://www.example.com/mizoram' },
    { id: 18, name: 'Nagaland', state: 'Nagaland', content: 'Content for Nagaland', link: 'https://www.example.com/nagaland' },
    { id: 19, name: 'Odisha', state: 'Odisha', content: 'Content for Odisha', link: 'https://www.example.com/odisha' },
    { id: 20, name: 'Punjab', state: 'Punjab', content: 'Content for Punjab', link: 'https://www.example.com/punjab' },
    { id: 21, name: 'Rajasthan', state: 'Rajasthan', content: 'Content for Rajasthan', link: 'https://www.example.com/rajasthan' },
    { id: 22, name: 'Sikkim', state: 'Sikkim', content: 'Content for Sikkim', link: 'https://www.example.com/sikkim' },
    { id: 23, name: 'Tamil Nadu', state: 'Tamil Nadu', content: 'Content for Tamil Nadu', link: 'https://www.example.com/tamil-nadu' },
    { id: 24, name: 'Telangana', state: 'Telangana', content: 'Content for Telangana', link: 'https://www.example.com/telangana' },
    { id: 25, name: 'Tripura', state: 'Tripura', content: 'Content for Tripura', link: 'https://www.example.com/tripura' },
    { id: 26, name: 'Uttar Pradesh', state: 'Uttar Pradesh', content: 'Content for Uttar Pradesh', link: 'https://www.example.com/uttar-pradesh' },
    { id: 27, name: 'Uttarakhand', state: 'Uttarakhand', content: 'Content for Uttarakhand', link: 'https://www.example.com/uttarakhand' },
    { id: 28, name: 'West Bengal', state: 'West Bengal', content: 'Content for West Bengal', link: 'https://www.example.com/west-bengal' },
    { id: 29, name: 'Andaman and Nicobar Islands', state: 'Andaman and Nicobar Islands', content: 'Content for Andaman and Nicobar Islands', link: 'https://www.example.com/andaman-and-nicobar-islands' },
    { id: 30, name: 'Chandigarh', state: 'Chandigarh', content: 'Content for Chandigarh', link: 'https://www.example.com/chandigarh' },
    { id: 31, name: 'Dadra and Nagar Haveli and Daman and Diu', state: 'Dadra and Nagar Haveli and Daman and Diu', content: 'Content for Dadra and Nagar Haveli and Daman and Diu', link: 'https://www.example.com/dadra-and-nagar-haveli-and-daman-and-diu' },
    { id: 32, name: 'Lakshadweep', state: 'Lakshadweep', content: 'Content for Lakshadweep', link: 'https://www.example.com/lakshadweep' },
    { id: 33, name: 'Delhi', state: 'Delhi', content: 'Content for Delhi', link: 'https://www.example.com/delhi' }, 
    { id: 34, name: 'Item 34', state: 'Ladakh', content: 'Content for Ladakh' },
    { id: 35, name: 'Item 35', state: 'Lakshadweep', content: 'Content for Lakshadweep' },
    { id: 36, name: 'Item 36', state: 'Puducherry', content: 'Content for Puducherry' },
  ];
  
  export default items;
  